---
- name: Configure macports
  ansible.builtin.command:
    cmd: >
      ./configure
      --enable-readline
      --with-unsupported-prefix
      --prefix="{{ lookup('env', 'XDG_STATE_HOME') }}/macports"
      --with-no-root-privileges
      --with-macports-user="{{ whoami }}"
      --with-applications-dir="{{ lookup('env', 'XDG_STATE_HOME') }}/macports/Applications"
      --with-frameworks-dir="{{ lookup('env', 'XDG_STATE_HOME') }}/macports/Frameworks"
    chdir: "{{ lookup('env', 'XDG_DATA_HOME') }}/macports"
  listen: "macports updated"
  changed_when: true

- name: Make macports
  ansible.builtin.command:
    cmd: "make"
    chdir: "{{ lookup('env', 'XDG_DATA_HOME') }}/macports"
  listen: "macports updated"
  changed_when: true

- name: Make install macports
  ansible.builtin.command:
    cmd: "make install"
    chdir: "{{ lookup('env', 'XDG_DATA_HOME') }}/macports"
  listen: "macports updated"
  changed_when: true

- name: Make distclean macports
  ansible.builtin.command:
    cmd: "make distclean"
    chdir: "{{ lookup('env', 'XDG_DATA_HOME') }}/macports"
  listen: "macports updated"
  changed_when: true
