---
# yaml-language-server: $schema: https://raw.githubusercontent.com/mattn/efm-langserver/master/schema.json
version: 2
root-markers:
  - .git/

tools:
  go-golines: &go-golines
    format-command: "golines --base-formatter=gofumpt --max-len=80 --shorten-comments"
    format-stdin: true

  json-fixjson: &json-fixjson
    format-command: "fixjson --stdin-filename ${INPUT}"
    format-stdin: true

  lua-stylua: &lua-stylua
    format-command: "stylua --search-parent-directories --stdin-filepath ${INPUT} -- -"
    format-stdin: true
    root-markers:
      - .stylua.toml

  prettier: &prettier
    format-command: "npx --no prettier -- --stdin-filepath ${INPUT}"
    format-stdin: true
    root-markers:
      - package.json

  ps1-pseditorservices: &ps1-pseditorservices
    format-command: "PowerShellEditorServices /powershell_sa/Invoke-Formatter"
    format-stdin: true

  python-ruff: &python-ruff
    format-command: "ruff format --quiet --stdin-filename ${INPUT} -"
    format-stdin: true
    root-markers:
      - pyproject.toml

  python-ruff-isort: &python-ruff-isort
    format-command: "ruff check --quiet --fix-only --select I,COM812,COM819 --stdin-filename ${INPUT} -"
    format-stdin: true
    root-markers:
      - pyproject.toml

  sh-shfmt: &sh-shfmt
    format-command: "shfmt --simplify --filename ${INPUT} -"
    format-stdin: true

  yaml-yamlfmt: &yaml-yamlfmt
    format-command: "yamlfmt -"
    format-stdin: true

languages:
  go:
    - !!merge <<: *go-golines

  html:
    - !!merge <<: *prettier

  javascript:
    - !!merge <<: *prettier

  json:
    - !!merge <<: *json-fixjson

  lua:
    - !!merge <<: *lua-stylua

  ps1:
    - !!merge <<: *ps1-pseditorservices

  python:
    - !!merge <<: *python-ruff
    - !!merge <<: *python-ruff-isort

  sh:
    - !!merge <<: *sh-shfmt

  yaml:
    - !!merge <<: *yaml-yamlfmt
