#!/bin/bash

source "$SRC/shared/04-install-zsh"

grep 'dotfiles/zsh/shared-host' "$HOME/.zshrcfiles/local.zsh" &> /dev/null || \
echo "antigen bundle brycekbargar/dotfiles dotfiles/zsh/shared-host" >>  "$HOME/.zshrcfiles/local.zsh"

log_trace 'Symlinking ssh-add-expect script'
sudo ln -sf "$DOTFILES/zsh/shared-host/ssh-add-expect" /usr/local/bin/ssh-add-expect

log_trace 'Setting lpass username in local settings'
grep 'LASTPASS_USERNAME' "$HOME/.zshrcfiles/local.zsh" > /dev/null || \
echo "export LASTPASS_USERNAME=\"$LASTPASS_USERNAME\"" >>  "$HOME/.zshrcfiles/local.zsh"

