#!/usr/bin/zsh

function bw-ssh-keygen(){
    local session="$(bw unlock --raw)"

    if [[ $(bw list items --search "$1" --folderid 5f327073-d3b6-4940-9783-a9db0022589e --session="$session" | jq '.[0]') != 'null' ]]; then
        echo "$1 key already exists in bitwarden"
        bw lock
        return
    fi

    local pw="$(bw generate -ulns --length 31)"
    echo "$pw" | clip.exe

    /usr/bin/ssh-keygen -f "$HOME/.ssh/$1" -t rsa -b 4096 -C "${2:-brycekbargar@gmail.com}"

    local itemid=$(bw get template item --session "$session" |
        jq --arg NAME "$1" --arg PW "$pw" '.name = $NAME | .notes = "" | .folderId="5f327073-d3b6-4940-9783-a9db0022589e" | .login = { "password": $PW }' |
        bw encode --session "$session" | bw create item --session "$session"|
        jq -r ' .id ')

    bw create attachment --file "$HOME/.ssh/$1" --itemid "$itemid" --session="$session" > /dev/null
    bw create attachment --file "$HOME/.ssh/$1.pub" --itemid "$itemid" --session="$session" > /dev/null

    bw lock
}