#!/usr/bin/zsh

function bw-ssh-add(){

    if ! env | grep -i SSH_AUTH_SOCK > /dev/null; then
        echo "Could not open a connection to your authentication agent."
        return
    fi
    
    bw list items --search "$1" --folderid 5f327073-d3b6-4940-9783-a9db0022589e | 
        jq -r '.[0].login.password' |
        clip.exe

    /usr/bin/ssh-add "$HOME/.ssh/$1"
}