#!/bin/zsh

function ssh-add (){

  target="$1"
  if [ ! "$1" ] || [ "$1" = "--host" ]; then
    target=$(uname -n)
  fi

  local pw=$(bw list items --search "$target" --folderid 5f327073-d3b6-4940-9783-a9db0022589e | jq '.[0].login.password')

  if [ ! -e "$HOME/.ssh/$target" ] || pw==null ; then
    echo $'Bad key name' >&2
    return 1
  fi

  expect ssh-add-expect -- "$HOME/.ssh/$target" "$pw"
}
