#!/bin/bash
# Sets things up for the installation script

requires () {
  source $@
}

for thisPath in "$(pwd)/src/applications" "$(pwd)/src/utilities" "$(pwd)/src/ssh-keys"; do
  case ":$PATH:" in
    *":$thisPath:"*) :;; # already there
    *) PATH="$PATH:$thisPath";;
  esac
done

export DOTFILES_DIR="$(pwd)/dotfiles"