[envs.cli]
channels = ["conda-forge"]
dependencies = { bat = "<0.27", exa = "==0.10.1", fd-find = "<10.5", fzf = "<0.68", git-delta = "<0.20", gojq = "<0.13", osc = "<0.5", precious = "<0.11", ripgrep = "<15.2" }
exposed = { bat = "bat", exa = "exa", fd = "fd", fzf = "fzf", delta = "delta", jq = "gojq", osc = "osc", precious = "precious", rg = "rg" }

[envs.ide]
channels = ["conda-forge"]
dependencies = { efm-langserver = "<0.0.57", go-shfmt = "<3.14", pre-commit-hooks = "<5.1", shellcheck = "<0.12", stylua = "<2.5", taplo = "<0.11", tree-sitter-cli = "<0.27", yamlfmt = "<0.22", yamllint = "<1.39" }
exposed = { efm-langserver = "efm-langserver", shfmt = "shfmt", check-added-large-files = "check-added-large-files", check-case-conflict = "check-case-conflict", end-of-file-fixer = "end-of-file-fixer", trailing-whitespace-fixer = "trailing-whitespace-fixer", shellcheck = "shellcheck", stylua = "stylua", taplo = "taplo", tree-sitter = "tree-sitter", yamlfmt = "yamlfmt", yamllint = "yamllint" }
