#:schema ./precious-schema.json

[commands.shfmt]
type = "both"
include = [
  "XDG_BIN_HOME/*",
  "XDG_CONFIG_HOME/git/hooks/*",
  "*.sh",
  "XDG_CONFIG_HOME/zsh/*.zsh",
  "XDG_CONFIG_HOME/zsh/functions/*",
]
exclude = ["**/myrc.zsh", "**/bw-ssh-add"]
cmd = ["umamba", "run", "--prefix", "$CONDA_ENVS/nvim", "shfmt"]
lint_flags = ["--diff"]
tidy_flags = ["--write", "--simplify"]
ok_exit_codes = [0]
expect_stderr = true
[commands.shellcheck]
type = "lint"
include = [
  "XDG_BIN_HOME/*",
  "XDG_CONFIG_HOME/git/hooks/*",
  "*.sh",
  "XDG_CONFIG_HOME/zsh/*.zsh",
  "XDG_CONFIG_HOME/zsh/functions/*",
]
exclude = ["**/myrc.zsh", "**/bw-ssh-add", "**/prompt.zsh"]
cmd = [
  "umamba",
  "run",
  "--prefix",
  "$CONDA_ENVS/nvim",
  "shellcheck",
  "--color=always",
]
ok_exit_codes = [0]
expect_stderr = true

[commands.vint]
type = "lint"
include = ["**/*.vim"]
cmd = [
  "pipx",
  "run",
  "--spec",
  "vim-vint",
  "vint",
  "--color",
  "--style-problem",
]
ok_exit_codes = [0]
expect_stderr = true
[commands.stylua]
type = "both"
include = ["XDG_CONFIG_HOME/nvim/lua/**/*.lua"]
cmd = [
  "umamba",
  "run",
  "--prefix",
  "$CONDA_ENVS/nvim",
  "stylua",
  "--color=always",
]
lint_flags = ["--check", "--verify"]
ok_exit_codes = [0]
expect_stderr = true

[commands."pre-comit.end-of-file"]
type = "tidy"
include = ["*"]
cmd = ["pipx", "run", "--spec", "pre-commit-hooks", "end-of-file-fixer"]
ok_exit_codes = [0, 1]
expect_stderr = true
[commands."pre-commit.trailing-whitespace"]
type = "tidy"
include = ["*"]
cmd = ["pipx", "run", "--spec", "pre-commit-hooks", "trailing-whitespace-fixer"]
ok_exit_codes = [0, 1]
expect_stderr = true

[commands.prettier]
type = "both"
include = ["*.json", "*.jsonc", "*.yaml", "*.yml"]
exclude = ["playbooks/*"]
cmd = ["npx", "--", "prettier@latest"]
lint_flags = ["--check"]
tidy_flags = ["--write"]
ok_exit_codes = [0]
expect_stderr = true

[commands."taplo.format"]
type = "both"
include = ["*.toml"]
cmd = [
  "umamba",
  "run",
  "--prefix",
  "$CONDA_ENVS/nvim",
  "taplo",
  "format",
  "--colors=always",
]
lint_flags = ["--check"]
ok_exit_codes = [0]
expect_stderr = true
[commands."taplo.lint-precious"]
type = "lint"
include = ["precious.toml"]
cmd = [
  "umamba",
  "run",
  "--prefix",
  "$CONDA_ENVS/nvim",
  "taplo",
  "check",
  "--colors=always",
  "--schema=https://raw.githubusercontent.com/brycekbargar/dotfiles/main/precious-schema.json",
]
ok_exit_codes = [0]
expect_stderr = true

[commands.ansible-lint]
type = "both"
include = ["playbooks/**/*.yaml", "playbooks/**/*.yml"]
cmd = ["ansible-lint", "--force-color", "-c", "playbooks/.ansible-lint"]
tidy_flags = ["--write", "-q"]
ok_exit_codes = [0, 2]
