[commands.shfmt]
type="both"
include = ["XDG_BIN_HOME/*", "XDG_CONFIG_HOME/git/hooks/*", "*.sh"]
cmd=["umamba", "run", "--prefix", "$CONDA_ENVS/nvim", "shfmt"]
lint_flags=["--diff"]
tidy_flags=["--write"]
ok_exit_codes = [0]
expect_stderr = true

[commands.vint]
type="lint"
include = "**/*.vim"
cmd = ["pipx", "run", "--spec", "vim-vint", "vint", "--color", "--style-problem"]
ok_exit_codes = [0]
expect_stderr = true
