#:schema ./precious-schema.json

[commands.shfmt]
type = "both"
include = [
  "XDG_BIN_HOME/*",
  "XDG_CONFIG_HOME/git/hooks/*",
  "*.sh",
  "XDG_CONFIG_HOME/zsh/*.zsh",
  "XDG_CONFIG_HOME/zsh/functions/*",
]
exclude = ["**/myrc.zsh", "**/bw-ssh-add", "**/.gitignore"]
cmd = ["conda-system", "nvim", "shfmt"]
lint_flags = ["--diff"]
tidy_flags = ["--write", "--simplify"]
ok_exit_codes = [0]
ignore_stderr = ["Waiting for other mamba process to finish"]
[commands.shellcheck]
type = "lint"
include = [
  "XDG_BIN_HOME/*",
  "XDG_CONFIG_HOME/git/hooks/*",
  "*.sh",
  "XDG_CONFIG_HOME/zsh/*.zsh",
  "XDG_CONFIG_HOME/zsh/functions/*",
]
exclude = ["**/myrc.zsh", "**/bw-ssh-add", "**/prompt.zsh", "**/.gitignore"]
cmd = ["conda-system", "nvim", "shellcheck", "--color=always"]
ok_exit_codes = [0]
ignore_stderr = ["Waiting for other mamba process to finish"]

[commands.vint]
type = "lint"
include = ["**/*.vim"]
cmd = [
  "pipx",
  "run",
  "--spec",
  "vim-vint",
  "vint",
  "--color",
  "--style-problem",
]
ok_exit_codes = [0]
ignore_stderr = ["Waiting for other mamba process to finish"]
[commands.stylua]
type = "both"
include = ["XDG_CONFIG_HOME/nvim/lua/**/*.lua"]
cmd = ["conda-system", "nvim", "stylua", "--color=always"]
lint_flags = ["--check", "--verify"]
ok_exit_codes = [0]
ignore_stderr = ["Waiting for other mamba process to finish"]

[commands."pre-comit.end-of-file"]
type = "tidy"
include = ["*"]
cmd = ["pipx", "run", "--spec", "pre-commit-hooks", "end-of-file-fixer"]
ok_exit_codes = [0, 1]
ignore_stderr = ["Waiting for other mamba process to finish"]
[commands."pre-commit.trailing-whitespace"]
type = "tidy"
include = ["*"]
cmd = ["pipx", "run", "--spec", "pre-commit-hooks", "trailing-whitespace-fixer"]
ok_exit_codes = [0, 1]
ignore_stderr = ["Waiting for other mamba process to finish"]

[commands.prettier]
type = "both"
include = ["*.json", "*.jsonc", "*.yaml", "*.yml"]
exclude = ["playbooks/*"]
cmd = ["npx", "--", "prettier@latest"]
lint_flags = ["--check"]
tidy_flags = ["--write"]
ok_exit_codes = [0]
ignore_stderr = ["Waiting for other mamba process to finish"]

[commands."taplo.format"]
type = "both"
include = ["*.toml"]
cmd = ["conda-system", "nvim", "taplo", "format", "--colors=always"]
lint_flags = ["--check"]
ok_exit_codes = [0]
ignore_stderr = ["Waiting for other mamba process to finish", "found files"]
[commands."taplo.lint-precious"]
type = "lint"
include = ["precious.toml"]
cmd = [
  "conda-system",
  "nvim",
  "taplo",
  "check",
  "--colors=always",
  "--schema=https://raw.githubusercontent.com/brycekbargar/dotfiles/main/precious-schema.json",
]
ok_exit_codes = [0]
ignore_stderr = ["Waiting for other mamba process to finish", "found files"]

[commands.ansible-lint]
type = "both"
include = ["playbooks/**/*.yaml", "playbooks/**/*.yml"]
cmd = ["ansible-lint", "--force-color", "-c", "playbooks/.ansible-lint"]
tidy_flags = ["--write", "-q"]
ok_exit_codes = [0, 2]
