#!/bin/bash

export ZSH_INSTALL_COMMAND='sudo pacman -S zsh'
export ZSH_EXECUTABLE_LOCATION='/usr/bin/zsh'
source "$SRC/shared/05-install-zsh"

grep "dotfiles/zsh/linux" "$HOME/.zshrcfiles/local.zsh" &> /dev/null || \
echo "antigen bundle brycekbargar/dotfiles dotfiles/zsh/linux" >>  "$HOME/.zshrcfiles/local.zsh"

