#!/usr/bin/zsh

export XDG_CONFIG_HOME="$HOME"/.config
export XDG_CACHE_HOME="$HOME"/.cache
export XDG_DATA_HOME="$HOME"/.local/share
export XDG_STATE_HOME="$HOME"/.local/state
export XDG_BIN_HOME="$HOME"/.local/bin

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

typeset -aU path
path=($XDG_BIN_HOME $path)
# Remove windows paths in wsl
path=(${path[@]:#*/mnt/c/Users/`whoami`*})
path=(${path[@]:#*/mnt/c/Windows})
path=(${path[@]:#*/mnt/c/Windows/System32/*})
path=(${path[@]:#*/mnt/c/Program Files/*})
