#!/usr/bin/zsh

export \
    XDG_CONFIG_HOME="$HOME/.local/etc" \
    XDG_DATA_HOME="$HOME/.local/share" \
    XDG_CACHE_HOME="$HOME/.local/var/cache" \
    XDG_STATE_HOME="$HOME/.local/var/lib" \
    XDG_BIN_HOME="$HOME/.local/bin"

export \
    CARGO_HOME="$XDG_CACHE_HOME/cargo" \
    CARGO_TARGET_DIR="$XDG_STATE_HOME/cargo" \
    CARGO_INSTALL_ROOT="$XDG_BIN_HOME/.."  # /bin is assumed by cargo
export \
    CONDA_ROOT="$XDG_STATE_HOME/conda" \
    CONDA_PKGS_DIRS="$XDG_CACHE_HOME/conda" \
    CONDA_ENVS_PATH="$XDG_STATE_HOME/conda:$XDG_DATA_HOME/conda" \
export \
    GOPATH="$XDG_STATE_HOME/go" \
    GOMODCACHE="$XDG_CACHE_HOME/go-mod" \
    GOBIN="$XDG_BIN_HOME"
export \
    NPM_CONFIG_CACHE="$XDG_CACHE_HOME/npm" \
    NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/.npmrc" \
    NPM_CONFIG_INIT_MODULES="$XDG_CONFIG_HOME/npm/.npm.init.js" \
    NPM_CONFIG_GLOBAL=true \
    NPM_CONFIG_PREFIX="$XDG_BIN_HOME/.."  # /bin is assumed by npm
export \
    STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship.toml" \
    STARSHIP_CACHE="$XDG_STATE_HOME/starship"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

typeset -aU path
# Remove windows paths in wsl
path=(${path[@]:#*/mnt/c/*})
path=($XDG_BIN_HOME $path "/mnt/c/Users/`id -un`/scoop/shims/" "/mnt/c/Windows/system32")
