---
- name: Create homebrew environment
  ansible.builtin.shell:
    cmd: "CONDA_ENVS_PATH='{{ lookup('env', 'CONDA_SYSTEM') }}' conda create --name installers-homebrew ruby=2.7 c-compiler cxx-compiler --yes"
    creates: "{{ lookup('env', 'CONDA_SYSTEM') }}/homebrew"

- name: Download homebrew
  ansible.builtin.git:
    repo: "https://github.com/Homebrew/brew.git"
    version: "HEAD"
    force: true
    dest: "{{ lookup('env', 'CONDA_SYSTEM') }}/installers-homebrew/brew"
    single_branch: true
    depth: 1

- name: Link homebrew bin
  ansible.builtin.file:
    src: "{{ lookup('env', 'CONDA_SYSTEM') }}/installers-homebrew/brew/bin"
    dest: "{{ lookup('env', 'XDG_PKG_HOME') }}/homebrew"
    state: link

- name: Set shellenv
  ansible.builtin.command:
    cmd: |
      conda env config vars set \
      {{ item.var }}={{ lookup('env', 'CONDA_SYSTEM') }}/installers-homebrew/{{ item.value }}
  with_items:
    - var: HOMEBREW_PREFIX
      value: brew
    - var: HOMEBREW_CELLAR
      value: brew/Cellar
    - var: HOMEBREW_REPOSITORY
      value: brew
  changed_when: true

- name: First time install homebrew
  ansible.builtin.shell:
    cmd: |
      conda run --name installers-homebrew \
      HOMEBREW_NO_ENV_FILTERING=1 \
      HOMEBREW_USE_RUBY_FROM_PATH=1 \
      {{ lookup('env', 'CONDA_SYSTEM') }}/installers-homebrew/brew/bin/brew update --force --quiet
  changed_when: false

- name: First time brew deps
  ansible.builtin.shell:
    cmd: |
      conda run --name installers-homebrew \
      HOMEBREW_NO_ENV_FILTERING=1 \
      HOMEBREW_USE_RUBY_FROM_PATH=1 \
      {{ lookup('env', 'CONDA_SYSTEM') }}/installers-homebrew/brew/bin/brew install curl git --quiet
  changed_when: false

- name: Brew Dr.
  ansible.builtin.command:
    cmd: brew doctor
    register: brew_doctor
  changed_when: true

- name: Brew Dr. stdout
  ansible.builtin.debug:
    var: brew_doctor
  changed_when: true

- name: Full brew update/upgrade
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
