HISTFILE=${HISTFILE:-"$HOME"/.zshrcfiles/history}
HISTSIZE=10000
SAVEHIST=10000

setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY

setopt HIST_ALLOW_CLOBBER
setopt HIST_REDUCE_BLANKS

setopt HIST_IGNORE_ALL_DUPS
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_SAVE_NO_DUPS
setopt HIST_FIND_NO_DUPS
