#!/bin/bash

sudo apt-get --yes install openssl libcurl4-openssl-dev libxml2 libssl-dev libxml2-dev pinentry-curses xclip
sudo apt-get --yes install --reinstall make

pushd "$SRC/lastpass-cli"
  if ! sudo make install PREFIX=/usr/local; then
    log_error $'Couldn\'t install lpass'

    exit 1
  fi
  if ! sudo make install-doc PREFIX=/usr/local; then
    log_warning $'Couldn\'t install lpass manpages'
  fi
popd

if ! lpass login $LASTPASS_USERNAME; then
  log_error $'Couldn\'t login to lpass'

  exit 1
fi

