#!/bin/bash

sudo apt-get --yes install openssl libcurl4-openssl-dev libxml2 libssl-dev libxml2-dev pinentry-curses xclip

export PREFIX="/usr/local"
pushd "$SRC/lastpass-cli"
  if ! make; then
    log_error $'Couldn\'t build lpass'

    exit 1
  fi
  if ! sudo make install; then
    log_error $'Couldn\'t install lpass'

    exit 1
  fi
  if ! sudo make install-doc; then
    log_warning $'Couldn\'t install lpass manpages'
  fi
popd

if ! lpass login $LASTPASS_USERNAME; then
  log_error $'Couldn\'t login to lpass'

  exit 1
fi

