#!/bin/bash

export ZSH_INSTALL_COMMAND='sudo apt-get --yes install zsh'
export ZSH_EXECUTABLE_LOCATION='/usr/bin/zsh'
source "$SRC/shared/05-install-zsh"

log_trace 'Setting .bashrc to launch zsh on start'
grep 'exec zsh' "$HOME/.bashrc" > /dev/null || \
echo "exec zsh" >> "$HOME/.bashrc"

log_trace 'Setting lpass username in local settings'
grep 'LASTPASS_USERNAME' "$HOME/.zshrcfiles/local.zsh" > /dev/null || \
echo "export LASTPASS_USERNAME=\"$LASTPASS_USERNAME\"" >>  "$HOME/.zshrcfiles/local.zsh"
