---
- name: Remove default repos
  become: true
  ansible.builtin.apt_repository:
    update_cache: false
    install_python_apt: false
    repo: "{{ item }}"
    state: absent
  with_items:
    - deb http://deb.debian.org/debian bullseye main
    - deb http://deb.debian.org/debian bullseye-updates main
    - deb http://security.debian.org/debian-security bullseye-security main
    - deb http://ftp.debian.org/debian bullseye-backports main

- name: Add repos
  become: true
  ansible.builtin.apt_repository:
    update_cache: false
    install_python_apt: false
    repo: "{{ item }}"
    state: present
  with_items:
    - deb http://deb.debian.org/debian testing main
    - deb-src http://deb.debian.org/debian testing main
    - deb http://deb.debian.org/debian testing-backports main
    - deb http://deb.debian.org/debian testing-updates main
    - deb http://security.debian.org/debian-security testing-security contrib main non-free
    - deb http://deb.debian.org/debian stable main
    - deb http://deb.debian.org/debian unstable main
    - deb http://deb.debian.org/debian experimental main

- name: Link preferences
  become: true
  ansible.builtin.file:
    src: "{{ debian }}/etc/apt/preferences"
    dest: "/etc/apt/preferences"
    state: link

- name: Full system upgrade
  become: true
  ansible.builtin.apt:
    update_cache: true
    autoremove: true
    upgrade: full

- name: Install required system packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - build-essential
      - pkg-config
      - libssl-dev
      - gnupg
      - unzip
    # TODO: Figure out why ansible doesn't respect preferences
    default_release: testing
    state: latest
