#!/usr/bin/env bash

conda run --name installers-homebrew --no-capture-output \
	HOMEBREW_CASK_OPTS="--greedy --no-binaries --no-quarantine --appdir='$XDG_PKG_HOME/homebrew-cask/apps' --fontdir='$XDG_PKG_HOME/homebrew-cask/fonts'" \
	HOMEBREW_AUTOREMOVE=1 \
	HOMEBREW_BOOTSNAP=1 \
	HOMEBREW_FORCE_BREWED_CURL=1 \
	HOMEBREW_FORCE_BREWED_GIT=1 \
	HOMEBREW_NO_AUTO_UPDATE=1 \
	HOMEBREW_NO_COMPAT=1 \
	HOMEBREW_NO_EMOJI=1 \
	HOMEBREW_NO_INSTALL_CLEANUP=1 \
	HOMEBREW_NO_INSTALL_UPGRADE=1 \
	HOMEBREW_VERBOSE_USING_DOTS=1 \
	HOMEBREW_USE_RUBY_FROM_PATH=1 \
	"$HOMEBREW_PREFIX/bin/brew" "$@"
