#!/bin/bash
#
# Installs all the packages required for a given environment
#
requires environment-name

case "$ENVIRONMENT" in
  'arch')
    requires pacman-package-manager
    pacman_init

    pacman_install openssh
    pacman_install pinentry
    pacman_install lastpass-cli
  ;;
  'mac')
    requires homebrew-package-manager
    homebrew_init
    requires homebrew-github-api-token

    homebrew_install google-chrome
    homebrew_install sonos
    homebrew_install ynab
    homebrew_install iterm2
    homebrew_install seil
    homebrew_install pinentry
    homebrew_install lastpass-cli
  ;;
  *)
    log_error $'We don\'t know what system you are on'
    exit 1
  ;;
esac