#!/bin/bash
#
# Exports
#   homebrew_init
#   homebrew_install
#
# A wrapper for homebrew and homebrew cask
#
requires log-writer

# Ensures that the homebrew and homebrew cask are installed and updated
homebrew_init () {
  if ! which brew; then
    log_trace 'We need to get homebrew'
    xcode-select --install
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew cask
  fi

  brew update && brew cleanup

  log_message 'You have homebrew'
}
export -f homebrew_init

# Tries to install the package from homebrew and homebrew cask
# Arguments
#   $1 package-name
#   $2 additional-package-source TODO: figure out how to handle additional package sources
# Returns
#   0 Package was installed
#   1 Package was not installed
homebrew_install () {
  # first check if it is installed
  if [ ! $(brew list | grep "$1") ] && [ ! $(brew cask list | grep "$1") ]; then

    case $(brew search $1) in
      *Caskroom/*/"$1"*)
        log_trace "Installing $1 from homebrew cask"
        if ! brew cask install $1; then
          log_warning "homebrew cask couldn't install $1"
          return 1
        fi
      ;;

      *"$1"*)
        log_trace "Installing $1 from homebrew"
        if ! brew install $1; then
          log_warning "homebrew couldn't install $1"
          return 1
        fi
      ;;

      *)
        log_warning "homebrew couldn't find $1"
        return 1
      ;;
    esac
  else
    log_trace "$1 already installed"
    return 0;
  fi

  log_message "homebrew installed $1"
}
export -f homebrew_install
