#!/bin/bash
# Ensures that Homebrew knows about our API token so it stops complaining about searches
#
requires lastpass-installed
requires log-writer

if [ "$HOMEBREW_GITHUB_API_TOKEN" ]; then
	log_trace "Homebrew GitHub Api Token is already set"
	return 0
fi

export HOMEBREW_GITHUB_API_TOKEN=$(lpass show --password ApiKeys/GitHub)
log_message 'Your Homebrew GitHub Auth Token has been set'