#!/bin/bash
#
# Makes sure node is installed
#
requires log-writer
requires homebrew
homebrew_init

if ! homebrew_install 'node'; then
    log_error $'Couldn\'t install node and I don\'t know how to manually do it'
    exit 1
fi

npm_install_global() {
  npm list --silent -g "$1" > /dev/null || \
  npm install -g "$1" > /dev/null
}
export -f npm_install_global
