#!/bin/bash
#
# Sets the $ENVIRONMENT environment variable
#

if [ "$ENVIRONMENT" ]; then
  log_trace "$ENVIRONMENT found"
  return 0
fi
    
# Let's first figure out what system we're on and what the package manager is
if which pacman; then
  log_trace $'We\'re on Arch'
  export ENVIRONMENT=arch
elif which brew  || [[ "$OSTYPE" == "darwin"* ]]; then
  log_trace $'We\'re on a Mac'
  export ENVIRONMENT=mac
fi