#!/bin/bash
# Exports
#    package_installed
#
# Ensures that the distros package manager is installed
# Ensures that additional package manager components are installed
# Ensures that the PACKAGE_MANAGER environment variable is set
# 
# Dependencies
requires log-writer

# We have been through this before and don't need to install/update anything
if [ "$PACKAGE_MANAGER" ]; then
    log_trace "$PACKAGE_MANAGER found"
    return 0
fi
    
# Let's first figure out what system we're on and what the package manager is
if which pacman; then
    log_trace $'We\'re on Arch'
    export PACKAGE_MANAGER=pacman
elif which brew  || [[ "$OSTYPE" == "darwin"* ]]; then
    log_trace $'We\'re on a Mac'
    export PACKAGE_MANAGER=homebrew
fi

# Install helpers and make sure everything is up to date
case "$PACKAGE_MANAGER" in
    "pacman")
        if ! which packer; then
            log_trace 'We need to make packer'
            # Make packer
        fi
        pacman -Syy
    ;;
    "homebrew")
        if ! which brew; then
            log_trace 'We need to get homebrew'
            xcode-select --install
            ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        fi
        if ! brew list | grep brew-cask; then
            log_trace 'We need to get cask'
            brew install caskroom/cask/brew-cask
        fi

        brew update

        if brew outdated | grep brew-cask; then
            brew upgrade brew-cask
        fi
        
        brew cleanup && brew cask cleanup
    ;;
    *)
        log_error $'We couldn\'t find a package manager'
        exit 1
    ;;
esac

log_message "You have $PACKAGE_MANAGER"

# Installs the requested packege if available
# Arguments
#   $1 package-name 
#   $2 additional-package-source TODO: figure out how to handle additional package sources
# Returns
#   0 Package is definitely installed
#   1 Package is probably not installed
package_installed () {

    case "$PACKAGE_MANAGER" in
        "pacman")
            if pacman -Ss $1 | grep "/$1 "; then
                log_trace "Installing $1 from pacman"
                sudo pacman -S $1

            elif packer -Ss $1 | grep "/$1 "; then
                log_trace "Installing $1 from packer"
                packer -S $1

            elif packer -Ss $1 | grep "/$1-git"; then
                log_trace "Installing $1 from packer"
                packer -S "$1-git"
            else
                log_warning "pacman couldn't find $1"
                return 1
            fi 
        ;;
        "homebrew")
            case $(brew search $1) in
                Caskroom/*/"$1")
                    if brew cask list | grep $1 ; then
                        log_trace "Upgrading $1 from homebrew cask"
                        brew cask install --force $1

                    else
                        log_trace "Installing $1 from homebrew cask"
                        brew cask install $1    
                    fi
                ;;
                "$1")
                    if brew list $1 | grep $1 ; then
                        if brew outdated | grep $1; then
                            log_trace "Upgrading $1 from homebrew"
                            brew upgrade $1
                        fi
                    else
                        log_trace "Installing $1 from homebrew"
                        brew install $1
                    fi
                ;;
                *)
                    log_warning "homebrew couldn't find $1"
                    return 1
                ;;
            esac
        ;;
        *)
            log_error 'We dont know what $PACKAGE_MANAGER you are using!'
            exit 1
        ;;
    esac

    return $?
}
export -f package_installed