#!/bin/bash
#
# Makes sure the folder for additional configs is present
#
requires log-writer

if [ ! -d "$HOME/.zshrcfiles" ]; then
  log_trace 'Creating zshrcfiles'
  if ! mkdir -p "$HOME/.zshrcfiles"; then
    log_error $'Could\'t make zshrcfiles'
  fi
else
  log_trace 'Already have zshfiles'
fi

touch $HOME/.zshrcfiles/local.zsh

log_message 'zshrcfiles initialized'
