---
- name: Instal vim
  ansible.builtin.command:
    cmd: "condstall --global --with conda --yes -- vim"
    creates: "{{ lookup('env', 'CONDA_SYSTEM' ) }}/installers-conda/bin/vim"

- name: Ensure vim dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ lookup('env', 'XDG_STATE_HOME') }}/vim/backup"
    - "{{ lookup('env', 'XDG_STATE_HOME') }}/vim/swap"
    - "{{ lookup('env', 'XDG_STATE_HOME') }}/vim/undo"
    - "{{ lookup('env', 'HOME') }}/.vim/pack"

- name: Add common plugins
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    version: "HEAD"
    force: true
    dest: "{{ lookup('env', 'HOME') }}/.vim/pack/common/{{ item.dest }}"
    single_branch: true
    depth: 1
  with_items:
    - repo: "https://github.com/tpope/vim-sensible"
      dest: "start/sensible"
    - repo: "https://github.com/tpope/vim-vinegar"
      dest: "start/vinegar"
    - repo: "https://github.com/tpope/vim-sleuth"
      dest: "start/sleuth"
    - repo: "https://github.com/lifepillar/vim-mucomplete"
      dest: "start/mucomplete"
    - repo: "https://github.com/sheerun/vim-polyglot"
      dest: "opt/polyglot"
    - repo: "https://github.com/catppuccin/vim"
      dest: "opt/catppuccin-vim"
    - repo: "https://github.com/tpope/vim-flagship"
      dest: "opt/flagship"

- name: Linking .vimrc
  ansible.builtin.file:
    src: "{{ lookup('env', 'XDG_CONFIG_HOME') }}/nvim/init.vim"
    dest: "{{ lookup('env', 'HOME') }}/.vim/vimrc"
    state: link
