#!/bin/bash
#
# Ensures that Dropbox is installed on this system
#
requires lastpass-installed
requires log-writer

if which dropbox_uploader; then

	log_trace "Dropbox already installed"
	return 0
fi

dropbox_uploader () {
	$DOTFILES_DIR/../src/applications/Dropbox-Uploader/dropbox_uploader.sh $@
}
export -f dropbox_uploader > /dev/null

# We are setting these config values from lastpass so it "just works"
ln -sf "$DOTFILES_DIR/applications/.dropbox_uploader" "$HOME/.dropbox_uploader"

log_message 'dropbox_uploader is installed'
