#!/bin/bash
#
# Ensures that Dropbox is installed on this system
#
requires lastpass-installed
requires homebrew
homebrew_init
requires log-writer

if which dropbox_uploader; then

	log_trace "Dropbox already installed"
	return 0
fi

if ! homebrew_install dropbox-uploader; then

  log_error $'Couldn\'t install lastpass and I don\'t know how to manually do it'
  exit 1
fi

# We are setting these config values from lastpass so it "just works"
ln -sf "$DOTFILES_DIR/applications/.dropbox_uploader" "$HOME/.dropbox_uploader"

if ! dropbox_uploader list; then

	log_error 'Something went wrong and you might not have dropbox'
	exit 1
fi

log_message 'dropbox_uploader is installed'
