#!/bin/bash
# Ensures that Dropbox is installed on this system
#
# Dependencies
depends_on lastpass
requires package-installer
requires log-writer

if [ "$DROPBOX_INSTALLED" ]; then
	log_trace "Dropbox already installed"
	return 0
fi

if ! package_installed dropbox-uploader; then
    
	log_warning $'Your package manager couldn\'t install dropbox'

    if [ ! -e /usr/bin/dropbox_uploader.sh ]; then
		# Do a manual install
		git clone https://github.com/andreafabrizi/Dropbox-Uploader/
 		sudo mv Dropbox-Uploader/dropbox_uploader.sh /usr/bin/
 		pushd /usr/bin/
	 	chmod +x dropbox_uploader.sh
 		popd
 	fi
 	rm -fdr Dropbox-Uploader

 	dropbox_uploader () {
 		/usr/bin/dropbox_uploader.sh $@
 	}
fi

# We are setting these config values from lastpass so it "just works"
if [ ! -e ~/.dropbox_uploader ]; then
	ln -s "$DOTFILES_DIR/applications/.dropbox_uploader" ~/.dropbox_uploader
fi

if ! dropbox_uploader list; then

	log_error 'Something went wrong and you might not have dropbox'
	exit 1
fi

export DROPBOX_INSTALLED="true"
log_message 'Latest dropbox-uploader version installed'