#!/bin/bash
# Ensures that Lastpass is installed on this system
#
requires package-manager
requires log-writer
requires pinentry-installed

if [ ! "$LASTPASS_USERNAME" ]; then
	log_error 'You must set $LASTPASS_USERNAME'
	exit 1
fi

if ! try_install lastpass-cli; then

    #Try manual install?

    log_error 'Something went wrong and you might not have Lastpass'
    exit 1
fi

if [ ! -e "$HOME/.lpass/session_privatekey" ]; then
    if ! lpass login $LASTPASS_USERNAME; then

        log_error 'Something went wrong and you might not have Lastpass'
        exit 1
    fi
fi

log_message 'lpass is installed'