#!/bin/bash
# Ensures that Lastpass is installed on this system
#
# Dependencies
requires package-manager
requires log-writer

if [ ! "$LASTPASS_USERNAME" ]; then
	log_error 'You must set $LASTPASS_USERNAME'
	exit 1
fi

if [ "$LASTPASS_INSTALLED" ]; then
    log_trace "Lastpass already installed"
    return 0
fi

if try_install lastpass-cli; then

    if lpass sync || lpass login $LASTPASS_USERNAME; then
        lpass sync
        
        export LASTPASS_INSTALLED="true"	
		log_message 'Latest Lastpass version installed'

        return 0
    fi
fi

log_error 'Something went wrong and you might not have Lastpass'
exit 1