#!/bin/bash
# Ensures that Lastpass is installed on this system
#
requires homebrew
homebrew_init
requires log-writer
requires zshrcfiles-initialized

if [ ! "$LASTPASS_USERNAME" ]; then
	log_error 'You must set $LASTPASS_USERNAME'
	exit 1
fi

if which lpass; then
  log_trace "Lastpass already installed"
  return 0
# Custom install to grab pinentry
elif ! brew install lastpass-cli --with-pinentry; then
  log_error $'Couldn\'t install lastpass and I don\'t know how to manually do it'
  exit 1
fi

if [ ! -e "$HOME/.lpass/session_privatekey" ]; then
  if ! lpass login $LASTPASS_USERNAME; then
    log_error 'Something went wrong and you might not have Lastpass'
    exit 1
  fi
fi

if [ ! -e "$HOME/.zshrcfiles/.zsh_lpass" ]; then
  log_trace 'Copying zsh_lpass'
  # We're copying since we are going to modify the file
  cp "$DOTFILES_DIR/applications/.zsh_lpass" "$HOME/.zshrcfiles/.zsh_lpass"
  sed -i '' "s/<username>/$LASTPASS_USERNAME/g" "$HOME/.zshrcfiles/.zsh_lpass"
else
  log_trace 'Already have zsh_lpass'
fi

log_message 'lpass is installed'
