#!/bin/bash
# Ensures that Lastpass is installed on this system
#
requires homebrew
homebrew_init
requires log-writer
requires zshrcfiles-initialized

if [ ! "$LASTPASS_USERNAME" ]; then
	log_error 'You must set $LASTPASS_USERNAME'
	exit 1
fi

if which lpass; then
  log_trace "Lastpass already installed"
	if [ ! -e "$HOME/.lpass/session_privatekey" ]; then
    lpass login "$LASTPASS_USERNAME"
  fi
  return 0
# Custom install to grab pinentry
elif ! brew install lastpass-cli --with-pinentry; then
  log_error $'Couldn\'t install lastpass and I don\'t know how to manually do it'
  exit 1
fi

if [ ! -e "$HOME/.lpass/session_privatekey" ]; then
  if ! lpass login $LASTPASS_USERNAME; then
    log_error 'Something went wrong and you might not have Lastpass'
    exit 1
  fi
fi

log_message 'lpass is installed'
