#!/bin/bash
# Ensures that Lastpass is installed on this system
#
# Dependencies
requires package-manager
requires log-writer

if [ ! "$LASTPASS_USERNAME" ]; then
	log_error 'You must set $LASTPASS_USERNAME'
	exit 1
fi

if ! which lpass && ! try_install lastpass-cli; then

    #Try manual install?

    log_error 'Something went wrong and you might not have Lastpass'
    exit 1
fi

if find ~/.lpass -maxdepth 0 -empty | grep lpass > /dev/null; then
    if ! lpass login $LASTPASS_USERNAME; then

        log_error 'Something went wrong and you might not have Lastpass'
        exit 1
    fi
fi

log_message 'lpass is installed'