#!/bin/bash
# Ensures that Lastpass is installed on this system
#
requires package-manager
requires log-writer

if which pinentry; then
  log_trace 'Already have pinentry'
  return 0
elif ! try_install pinentry; then
    log_error $'Couldn\'t install pinentry and I don\'t know how to manually do it'
    exit 1
fi

log_message 'pinentry is installed'