#!/bin/bash
#
# Installs zsh and sets it as the default shell
#
requires log-writer
requires homebrew
homebrew_init

if [[ "$SHELL" =~ 'zsh' ]]; then
    log_trace 'Already have zsh'
    return 0;
elif ! homebrew_install 'zsh'; then
    log_error $'Couldn\'t install zsh and I don\'t know how to manually do it'
    exit 1
fi

if [ ! -e "$HOME/.zshrc" ]; then
  echo '' > "$HOME/.zshrc"
fi

if [[ ! "$SHELL" =~ 'zsh' ]]; then

  zsh_loc=/usr/local/bin/zsh

  if [ ! "$zsh_loc" ]; then
    log_error $'Couldn\t find zsh'
    exit 1
  fi

  if ! grep "$zsh_loc" /etc/shells; then
    sudo sh -c "echo '$zsh_loc' >> /etc/shells"
  fi

  chsh -s "$zsh_loc"
fi

log_message 'You have zsh'
