---
nvim_env_path: "{{ lookup('env', 'CONDA_ENVS') }}/nvim"
lua_lsp_pattern: "{{ ('linux-x64.tar.gz' if ansible_distribution == 'Debian' else 'darwin-' ~ ansible_architecture | replace('86_', '') ~ '.tar.gz') }}"
