#!/bin/bash
#
# Symlinks .zshrc
# Links other configs
#
requires log-writer
requires zshrcfiles-initialized
requires environment-name

if [ ! -e "$HOME/.zshrc" ] || ! grep '# bryces-dotfiles-zshrc' "$HOME/.zshrc"; then
  log_trace 'Copying my zshrc'

  if [ -e "$HOME/.zshrc" ]; then
    log_warning 'Removing existing zshrc'
    rm -f "$HOME/.zshrc"
  fi

  ln -s "$DOTFILES_DIR/zshrc/.zshrc" "$HOME/.zshrc"
else
  log_trace 'My zshrc already in place'
fi

case "$ENVIRONMENT" in
  'mac')
    if [ ! -e "$HOME/.zshrcfiles/.zsh_mac" ]; then
      ln -s "$DOTFILES_DIR/zshrc/.zsh_mac" "$HOME/.zshrcfiles/.zsh_mac"
    fi
    log_trace 'Linked zsh_mac settings' 
  ;;
esac

log_message 'zshrc setup'