#!/bin/bash
#
# Makes sure the folder for additional configs is present
#
requires log-writer

if [  -d "$HOME/.zshrcfiles" ]; then
  log_trace 'Already have zshfiles'
  return 0;
fi
  
log_trace 'Creating zshrcfiles'
  if ! mkdir -p "$HOME/.zshrcfiles"; then
    log_error $'Could\'t make zshrcfiles'
  fi
fi

log_message 'zshrcfiles initialized'