---
- name: Link .zshenv
  ansible.builtin.file:
    src: "{{ dotfiles }}/.zshenv"
    dest: "{{ lookup('env', 'HOME') }}/.zshenv"
    state: link

- name: Load additional .zshrc files
  ansible.builtin.blockinfile:
    path: "{{ lookup('env', 'ZDOTDIR') }}/.zshrc"
    marker: "# {mark} ANSIBLE MANAGED .myzshrc"
    create: true
    mode: "0644"
    insertbefore: BOF
    block: source "$ZDOTDIR/myrc.zsh"
    state: present
# TODO: Parameterize this

- name: Init conda
  ansible.builtin.command:
    cmd: conda init zsh
  changed_when: false

- name: Download antidote
  ansible.builtin.git:
    repo: https://github.com/mattmc3/antidote.git
    version: HEAD
    force: true
    dest: "{{ lookup('env', 'ANTIDOTE_SOURCE') }}"
    single_branch: true
