---
- name: Load additional .zshrc files
  ansible.builtin.blockinfile:
    path: "{{ lookup('env', 'ZDOTDIR') }}/.zshrc"
    marker: "# {mark} ANSIBLE MANAGED .myzshrc"
    create: true
    mode: "0644"
    insertbefore: "BOF"
    block: |
      source "$ZDOTDIR/.myzshrc"
    state: present
  # TODO: Parameterize this

- name: Init conda (again)
  ansible.builtin.command:
    cmd: "conda init zsh"
  changed_when: false

- name: Download antidote
  ansible.builtin.git:
    repo: "https://github.com/mattmc3/antidote.git"
    version: "HEAD"
    force: true
    dest: "{{ lookup('env', 'XDG_BIN_HOME') }}/antidote"
    single_branch: true
    depth: 1

- name: Install starship (cargo)
  ansible.builtin.command:
    cmd: condstall --with rust --global --yes -- starship --locked
  changed_when: true

- name: whoami fact
  become: false
  ansible.builtin.set_fact:
    whoami: "{{ ansible_user_id }}"

- name: chsh to zsh
  become: true
  ansible.builtin.user:
    name: "{{ whoami }}"
    shell: "/usr/bin/zsh"
  # TODO: Is it always /usr/bin/zsh? maybe a var?

- name: Start zsh in wsl
  ansible.builtin.blockinfile:
    path: "{{ lookup('env', 'HOME') }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    create: true
    mode: "0644"
    block: |
      exec /usr/bin/zsh --login
    state: present
  when: ansible_distribution == "Debian"
