---
- name: Load additional .zshrc files
  ansible.builtin.blockinfile:
    path: "{{ lookup('env', 'ZDOTDIR') }}/.zshrc"
    marker: "# {mark} ANSIBLE MANAGED .myzshrc"
    create: true
    mode: "0644"
    insertbefore: "BOF"
    block: |
      cd ~/
      source "$ZDOTDIR/myrc.zsh"
    state: present
  # TODO: Parameterize this

- name: Init conda (again)
  ansible.builtin.command:
    cmd: "conda init zsh"
  changed_when: false

- name: Download antidote
  ansible.builtin.git:
    repo: "https://github.com/mattmc3/antidote.git"
    version: "HEAD"
    force: true
    dest: "{{ lookup('env', 'XDG_BIN_HOME') }}/antidote"
    single_branch: true
    depth: 1

- name: chsh to zsh
  become: true
  ansible.builtin.user:
    name: "{{ whoami }}"
    shell: "{{ zsh }}"
  when: ansible_distribution == "Debian"
