---
- name: Load additional .zshrc files
  ansible.builtin.blockinfile:
    path: "{{ lookup('env', 'ZDOTDIR') }}/.zshrc"
    marker: "# {mark} ANSIBLE MANAGED .myzshrc"
    state: present
    insertbefore: "BOF"
    block: |
      source "$ZDOTDIR/.myzshrc"

- name: Download antidote
  ansible.builtin.git:
    repo: "https://github.com/mattmc3/antidote.git"
    version: "HEAD"
    force: true
    dest: "{{ lookup('env', 'ZDOTDIR') }}/.antidote"
    single_branch: true
    depth: 1

- name: Install starship
  ansible.builtin.command:
    cmd: "conda run -n base cargo install starship --locked"
    creates: "{{ lookup('env', 'XDG_BIN_HOME') }}/starship"
  changed_when: true

- name: Link starship config
  ansible.builtin.file:
    src: "{{ dotfiles }}/XDG_CONFIG_HOME/starship.toml"
    dest: "{{ lookup('env', 'XDG_CONFIG_HOME') }}/starship.toml"
    state: link

- name: Link inputrc
  ansible.builtin.file:
    src: "{{ dotfiles }}/XDG_CONFIG_HOME/.inputrc"
    dest: "{{ lookup('env', 'XDG_CONFIG_HOME') }}/.inputrc"
    state: link

- name: Link .myzsh files
  ansible.builtin.file:
    src: "{{ dotfiles }}/ZDOTDIR/{{ item }}"
    dest: "{{ lookup('env', 'ZDOTDIR') }}/{{ item }}"
    force: true
    state: link
  with_items:
    - ".myzshrc"
    - "functions"
    - "zshrc.d"
    - ".zsh_plugins.txt"
