#!/bin/bash
#
# Downloads the Identity keys from Dropbox
#
requires dropbox-installed
requires log-writer

if ! dropbox_uploader download "/SSHKeys/Identity" "$HOME/.ssh/"; then
    log_error $'Couldn\'t download ssh identity keys'
    exit 1
fi

mv "$HOME/.ssh/Identity/"* "$HOME/.ssh/"
rm -fd "$HOME/.ssh/Identity/"

log_message 'SSH Identity Keys are in sync'
