#!/bin/bash
#
# Checks to see if the host key is in dropbox or on the local system
# 
requires dropbox
requires hostname
requires ssh-key-utilities

if [ -e "~/.ssh/$HOSTNAME" ] && [ -e "~/.ssh/$HOSTNAME.pub" ]; then
    key_present='yes'
fi

if dropbox_uploader list SSHKeys/Host | grep $HOSTNAME; then
    key_in_dropbox='yes'
fi

if [ "$key_present" ] && [ "$key_in_dropbox" ]; then
    log_trace 'We have the key locally and in dropbox'
    return 0
fi

if [ "$key_in_dropbox" ]; then
    log_trace 'Downloading keys from dropbox'

    fail=0
    dropbox_uploader download "SSHKeys/Host/$HOSTNAME" "~/.ssh/$HOSTNAME" || fail=1
    dropbox_uploader download "SSHKeys/Host/$HOSTNAME.pub" "~/.ssh/$HOSTNAME.pub" || fail=1

    if ((fail)); then
        log_error $'Couldn\'t download ssh host keys from dropbox'
        exit 0
    fi
fi

if [ ! "$key_present" ]; then
    log_trace 'Creating keys'

    if ! create-ssh-key "~/.ssh/$HOSTNAME"; then
      log_error $'Couldn\'t create ssh hostkey'
      exit 0
    fi

    key_present='yes'
fi

if [ "$key_present" ]; then
    log_trace 'Uploading keys to dropbox'

    fail=0
    dropbox_uploader upload "~/.ssh/$HOSTNAME" "SSHKeys/Host/$HOSTNAME" || fail=1
    dropbox_uploader upload "~/.ssh/$HOSTNAME.pub" "SSHKeys/Host/$HOSTNAME.pub" || fail=1

    if ((fail)); then
      log_error $'Couldn\'t upload ssh host keys from dropbox'
      exit 0
    fi

    key_in_dropbox='yes'
fi

return 0;