#!/bin/bash
#
# Checks to see if the host key is in dropbox or on the local system
# 
requires log-writer
requires dropbox
requires current-hostname
requires ssh-key-utilities

if [ -e "$HOME/.ssh/$HOSTNAME" ] && [ -e "$HOME/.ssh/$HOSTNAME.pub" ]; then
    key_present='yes'
fi

if dropbox_uploader list SSHKeys/Host | grep $HOSTNAME; then
    key_in_dropbox='yes'
fi

if [ "$key_present" ] && [ "$key_in_dropbox" ]; then
    log_trace 'We have the key locally and in dropbox'
fi

if [ ! "$key_present" ] && [ "$key_in_dropbox" ]; then
    log_trace 'Downloading keys from dropbox'

    fail=0
    dropbox_uploader download "SSHKeys/Host/$HOSTNAME" "$HOME/.ssh/$HOSTNAME" || fail=1
    dropbox_uploader download "SSHKeys/Host/$HOSTNAME.pub" "$HOME/.ssh/$HOSTNAME.pub" || fail=1

    if ((fail)); then
        log_error $'Couldn\'t download ssh host keys from dropbox'
        exit 1
    fi

    key_present='yes'
fi

if [ ! "$key_present" ]; then
    log_trace 'Creating keys'

    if ! create_ssh_key "$HOSTNAME"; then
      log_error $'Couldn\'t create ssh hostkey'
      exit 1
    fi

    key_present='yes'
fi

if [ "$key_present" ] && [ ! "$key_in_dropbox" ]; then
    log_trace 'Uploading keys to dropbox'

    fail=0
    dropbox_uploader upload "$HOME/.ssh/$HOSTNAME" "SSHKeys/Host" || fail=1
    dropbox_uploader upload "$HOME/.ssh/$HOSTNAME.pub" "SSHKeys/Host" || fail=1

    if ((fail)); then
      log_error $'Couldn\'t upload ssh host keys to dropbox'
      exit 1
    fi

    key_in_dropbox='yes'
fi

if [ ! "$key_present" ] || [ ! "$key_in_dropbox" ]; then
  log_error $'SSH Host Keys not in sync'
  exit 1 
fi

log_message 'SSH Host Keys are in sync'