---
- name: Make condarc from template
  ansible.builtin.copy:
    src: "{{ dotfiles }}/XDG_CONFIG_HOME/conda/template"
    dest: "{{ lookup('env', 'CONDARC') }}"
    mode: "0644"

- name: Ensure channels
  ansible.builtin.blockinfile:
    path: "{{ lookup('env', 'CONDARC') }}"
    marker: "# {mark} ANSIBLE MANAGED CHANNELS"
    state: present
    insertafter: "channels:"
    block: |
      - conda-forge
      # TODO: Make this a var

- name: Linking umamba binary
  ansible.builtin.file:
    src: "{{ lookup('env', 'CONDA_SYSTEM') }}/base/bin/micromamba"
    dest: "{{ lookup('env', 'XDG_BIN_HOME') }}/umamba"
    state: link

- name: Link toolchain bins
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ lookup('env', 'XDG_PKG_HOME') }}/{{ item.toolchain }}"
    force: true
    state: link
  with_items:
    - src: "{{ lookup('env', 'CARGO_INSTALL_ROOT') }}/bin"
      toolchain: rust
    - src: "{{ lookup('env', 'GOPATH') }}/bin"
      toolchain: go
