---
- name: Make condarc from template
  ansible.builtin.copy:
    src: "{{ dotfiles }}/XDG_CONFIG_HOME/conda/template"
    dest: "{{ lookup('env', 'CONDARC') }}"
    mode: "0644"

- name: Ensure channels
  ansible.builtin.blockinfile:
    path: "{{ lookup('env', 'CONDARC') }}"
    marker: "# {mark} ANSIBLE MANAGED CHANNELS"
    state: present
    insertafter: "channels:"
    block: |
      - conda-forge
      # TODO: Make this a var

- name: Linking umamba binary
  ansible.builtin.file:
    src: "{{ lookup('env', 'XDG_STATE_HOME') }}/conda/base/bin/micromamba"
    dest: "{{ lookup('env', 'XDG_BIN_HOME') }}/umamba"
    state: link
