#!/bin/bash

if [[ "$SHELL" =~ 'zsh' ]]; then
  log_trace 'Already have zsh'

elif sh -c "$ZSH_INSTALL_COMMAND"; then
  zsh_loc=${ZSH_EXECUTABLE_LOCATION:-"$(which zsh)"}

  if ! grep "$zsh_loc" /etc/shells > /dev/null; then
    sudo sh -c "echo '$zsh_loc' >> /etc/shells"
  fi

  chsh -s "$zsh_loc"
  log_message 'You have zsh'

else
  log_error $'Couldn\'t install zsh...'

  exit 1
fi

log_trace 'Linking my zshrc'
ln -sf "$DOTFILES/zsh/.zshrc" "$HOME/.zshrc"
# I hate going ~/.zs -> tab and then only getting ~/.zsh
ln -sf "$DOTFILES/zsh/.zshrc" "$HOME/.zsh"

log_trace 'Linking zshenv'
ln -sf "$DOTFILES/zsh/.zshenv" "$HOME/.zshenv"

mkdir -p "$HOME/.zshrcfiles"
touch "$HOME/.zshrcfiles/local.zsh"

grep "dotfiles/zsh/$ENVIRONMENT" "$HOME/.zshrcfiles/local.zsh" &> /dev/null || \
echo "antigen bundle brycekbargar/dotfiles dotfiles/zsh/$ENVIRONMENT" >>  "$HOME/.zshrcfiles/local.zsh"

log_trace 'Linking antigen'
ln -sf "$LIB/antigen/antigen.zsh" "$HOME/.zshrcfiles/antigen.zsh"

log_trace 'Symlinking ssh-add-expect script'
sudo ln -sf "$DOTFILES/zsh/shared/ssh-add-expect" /usr/local/bin/ssh-add-expect

log_trace 'Setting lpass username in local settings'
grep 'LASTPASS_USERNAME' "$HOME/.zshrcfiles/local.zsh" > /dev/null || \
echo "export LASTPASS_USERNAME=\"$LASTPASS_USERNAME\"" >>  "$HOME/.zshrcfiles/local.zsh"

log_message 'zshrc setup'
