#!/bin/bash

log_trace 'Copying my gitconfig'
cp -f "$DOTFILES/git/.gitconfig" "$HOME/.gitconfig"

git config --global user.name "$GIT_NAME"
git config --global user.email "$GIT_EMAIL"

for thisFileName in "$DOTFILES/git/bin/"*; do
    thisFile=$(basename "$thisFileName")
    log_trace "Symlinking $thisFile"
    ln -sf "$DOTFILES/git/bin/$thisFile" "/usr/local/bin/$thisFile"
    log_message "$thisFile symlinked"
done

log_message 'gitconfig setup'
