#!/bin/bash

sudo apt --yes install openssl libcurl4-openssl-dev libxml2 libssl-dev libxml2-dev pinentry-curses xclip cmake build-essential pkg-config
sudo apt --yes install --reinstall make

pushd "$LIB/lastpass-cli"
  cmake . && make
  sudo make install PREFIX=/usr/local
popd

if ! lpass login $LASTPASS_USERNAME; then
  log_error $'Couldn\'t login to lpass'

  exit 1
fi

