#!/bin/bash

sudo apt install --yes expect

export ZSH_INSTALL_COMMAND='sudo apt --yes install zsh'
export ZSH_EXECUTABLE_LOCATION='/usr/bin/zsh'
source "$SRC/shared/04-install-zsh"

log_trace 'Setting .bashrc to launch zsh on start'
grep 'exec zsh' "$HOME/.bashrc" > /dev/null || \
echo "exec zsh" >> "$HOME/.bashrc"
