#!/bin/bash

sudo apt --yes install software-properties-common
sudo add-repository --yes ppa:neovim-ppa/unstable
sudo apt --yes update
sudo apt --yes install neovim

sudo update-alternatives --install /usr/bin/vi vi /usr/bin/nvim 60
sudo update-alternatives --config vi
sudo update-alternatives --install /usr/bin/vim vim /usr/bin/nvim 60
sudo update-alternatives --config vim
sudo update-alternatives --install /usr/bin/editor editor /usr/bin/nvim 60
sudo update-alternatives --config editor

source "$SRC/shared/07-install-neovim"
