#!/bin/zsh
#
# Sees if lpass is has login information
# Logs in if it doesn't
# Syncs before issuing command
#

lpass () {
  local bin_lpass=/usr/local/bin/lpass
  if [ ! -e "$HOME/.lpass/session_privatekey" ]; then
    $BIN_LPASS login <username>
  fi

  $BIN_LPASS sync
  $BIN_LPASS $@
}
