#!/bin/zsh
#
# Starts the ssh-agent and adds the decrypted keys from lastpass
#

function ssh-add (){

  if ! ps -e | grep '\d ssh-agent' > /dev/null; then
    eval `ssh-agent -s`
  fi

  target="$1"
  if [ ! "$1" ] || [ "$1" = "--host" ]; then
    target=$(uname -n)
  fi

  if [ ! -e "$HOME/.ssh/$target" ] || ! lpass ls | grep "$target" > /dev/null; then
    echo $'Bad key name' >&2
    return 1
  fi

  lpass show --password "$target" | pbcopy > /dev/null
  /usr/bin/ssh-add "$HOME/.ssh/$target"
}
