---
- name: Ensure channels
  ansible.builtin.blockinfile:
    path: "{{ lookup('env', 'XDG_CONFIG_HOME')/.condarc }}"
    marker: "# {mark} ANSIBLE MANAGED CHANNELS"
    state: present
    insertafter: "channels:"
    block: |
      - conda-forge

- name: Update conda
  ansible.builtin.command:
    cmd: "conda update --name base conda --yes"
  changed_when: true

- name: Update/install base env
  ansible.builtin.command:
    cmd: "conda env update --name base --file '{{ dotfiles }}/dot_local/etc/conda/environment.yml --prune --yes"
  changed_when: true

- name: Clean conda
  ansible.builtin.command:
    cmd: "conda clean --packages --yes"
  changed_when: true
