#!/bin/bash

if type log_warning >& /dev/null; then
  return 0
fi

log_step () {
  echo '======================='
  echo ''
  echo ''
  echo "### Running: $1 ###"
  echo '========================'
}
export -f log_step

log_error () {
  echo "error: $1 :("
}
export -f log_error

log_message () {
  echo "message: $1"'!'
}
export -f log_message

log_trace () {
  echo "trace: $1"
}
export -f log_trace

log_warning () {
  echo "warning: $1..."
}
export -f log_warning

