#!/bin/bash

if which brew > /dev/null || [[ "$OSTYPE" == "darwin"* ]]; then
  log_trace $'We\'re on a Mac'
  export ENVIRONMENT=osx

elif which apt > /dev/null || grep 'Microsoft' /proc/version > /dev/null; then
  log_trace $'We\'re on Ubuntu (possibly using windows...)'
  export ENVIRONMENT=ubuntu

fi


if [ -z "$ENVIRONMENT" ]; then
  log_error $'Couldn\'t set the ENVIRONMENT'

  exit 1
fi
