#!/bin/bash
#
# Symlinks .zshrc
# Sets up antigen and local zsh settings
#
requires log-writer
requires lastpass-installed

log_trace 'Linking my zshrc'
ln -sf "$DOTFILES_DIR/zsh/.zshrc" "$HOME/.zshrc"
# I hate going ~/.zs -> tab and then only getting ~/.zsh
ln -sf "$DOTFILES_DIR/zsh/.zshrc" "$HOME/.zsh"

log_trace 'Linking zshenv'
ln -sf "$DOTFILES_DIR/zsh/.zshenv" "$HOME/.zshenv"

mkdir -p "$HOME/.zshrcfiles"
touch "$HOME/.zshrcfiles/local.zsh"

log_trace 'Setting homebrew token in local settings'
grep 'HOMEBREW_GITHUB_API_TOKEN' "$HOME/.zshrcfiles/local.zsh" > /dev/null || \
echo "export HOMEBREW_GITHUB_API_TOKEN=$(lpass show --password ApiKeys/HomebrewToken)" >>  "$HOME/.zshrcfiles/local.zsh"

log_trace 'Setting lpass username in local settings'
grep 'LASTPASS_USERNAME' "$HOME/.zshrcfiles/local.zsh" > /dev/null || \
echo "export LASTPASS_USERNAME=$LASTPASS_USERNAME" >>  "$HOME/.zshrcfiles/local.zsh"

log_trace 'Linking antigen'
ln -sf "$DOTFILES_DIR/zsh/antigen/antigen.zsh" "$HOME/.zshrcfiles/antigen.zsh"

log_message 'zshrc setup'
