#!/bin/bash
#
# Sets up mac keybindings/keyboard
#
requires log-writer
requires homebrew
homebrew_init

homebrew_install seil
/Applications/Seil.app/Contents/Library/bin/seil set keycode_capslock 53

homebrew_install karabiner
cp -f "$DOTFILES_DIR/applications/private.xml" "$HOME/Library/Application\ Support/Karabiner/private.xml"
