#!/bin/bash
#
# Symlinks .gitconfig
# Sets up initial settings
# Adds the git cmds to the /bin path
#
requires log-writer

if [ ! "$GIT_NAME" ] || [ ! "$GIT_EMAIL" ]; then
  log_error '$GIT_NAME and $GIT_EMAIL are required'
  exit 1
fi

# We're copying since we don't want to check to modification into source
log_trace 'Copying my gitconfig'
cp -f "$DOTFILES_DIR/git/.gitconfig" "$HOME/.gitconfig"

git config --global user.name "$GIT_NAME"
git config --global user.email "$GIT_EMAIL"

for thisFileName in "$DOTFILES_DIR/git/bin/"*; do
    thisFile=$(basename "$thisFileName")
    log_trace "Symlinking $thisFile"
    ln -sf "$DOTFILES_DIR/git/bin/$thisFile" "/usr/local/bin/$thisFile"
    log_message "$thisFile symlinked"
done

log_message 'gitconfig setup'
