#!/bin/bash
#
# Symlinks Neovim Configs
#
requires log-writer

mkdir -p "$HOME/.config/nvim/autoload"

log_trace 'Linking init.vim'
ln -sf "$DOTFILES_DIR/nvim/init.vim" "$HOME/.config/nvim"

log_trace 'Linking vim-plug'
ln -sf "$DOTFILES_DIR/nvim/vim-plug/plug.vim" "$HOME/.config/nvim/autoload/plug.vim"

log_message 'nvim setup'
