#!/bin/bash
#
# Symlinks .gitconfig
# Sets up initial settings
# Copies and chmods git-* scripts
#

if ! grep '# bryces-dotfiles-gitconfig' "$HOME/.gitconfig"; then
  ln -s "$DOTFILES_DIR/git/.gitconfig" "$HOME/.gitconfig"
  git config --global user.name "$(whoami)"
  git config --global user.email "$LASTPASS_USERNAME"
fi
