#!/bin/bash

export ZSH_INSTALL_COMMAND='brew install zsh'
export ZSH_EXECUTABLE_LOCATION='/usr/local/bin/zsh'
source "$SRC/shared/host/04-install-zsh"

log_trace 'Setting homebrew token in local settings'
grep 'HOMEBREW_GITHUB_API_TOKEN' "$HOME/.zshrcfiles/local.zsh" > /dev/null || \
echo "export HOMEBREW_GITHUB_API_TOKEN=\"$(lpass show --password ApiKeys/HomebrewToken)\"" >>  "$HOME/.zshrcfiles/local.zsh"

grep "dotfiles/zsh/bsd" "$HOME/.zshrcfiles/local.zsh" &> /dev/null || \
echo "antigen bundle brycekbargar/dotfiles dotfiles/zsh/bsd" >>  "$HOME/.zshrcfiles/local.zsh"

pushd /usr/local/share/
sudo chmod -R 755 zsh
sudo chown -R root:staff zsh
popd
