#!/bin/bash

export ZSH_INSTALL_COMMAND='brew install zsh'
export ZSH_EXECUTABLE_LOCATION='/usr/local/bin/zsh'
source "$SRC/shared/05-install-zsh"

log_trace 'Setting homebrew token in local settings'
grep 'HOMEBREW_GITHUB_API_TOKEN' "$HOME/.zshrcfiles/local.zsh" > /dev/null || \
echo "export HOMEBREW_GITHUB_API_TOKEN=\"$(lpass show --password ApiKeys/HomebrewToken)\"" >>  "$HOME/.zshrcfiles/local.zsh"

log_trace 'Setting lpass username in local settings'
grep 'LASTPASS_USERNAME' "$HOME/.zshrcfiles/local.zsh" > /dev/null || \
echo "export LASTPASS_USERNAME=\"$LASTPASS_USERNAME\"" >>  "$HOME/.zshrcfiles/local.zsh"
