#!/bin/bash

if [[ "$SHELL" =~ 'zsh' ]]; then
  log_trace 'Already have zsh'

  return 0;
elif ! brew install zsh; then
  log_error $'Couldn\'t install zsh and I don\'t know how to manually do it'

  exit 1
fi

zsh_loc='/usr/local/bin/zsh'

if ! grep "$zsh_loc" /etc/shells; then
  sudo sh -c "echo '$zsh_loc' >> /etc/shells"
fi

chsh -s "$zsh_loc"
log_message 'You have zsh'

source "$SRC/shared/05-install-zsh"

log_trace 'Setting homebrew token in local settings'
grep 'HOMEBREW_GITHUB_API_TOKEN' "$HOME/.zshrcfiles/local.zsh" > /dev/null || \
echo "export HOMEBREW_GITHUB_API_TOKEN=\"$(lpass show --password ApiKeys/HomebrewToken)\"" >>  "$HOME/.zshrcfiles/local.zsh"

log_trace 'Setting lpass username in local settings'
grep 'LASTPASS_USERNAME' "$HOME/.zshrcfiles/local.zsh" > /dev/null || \
echo "export LASTPASS_USERNAME=\"$LASTPASS_USERNAME\"" >>  "$HOME/.zshrcfiles/local.zsh"
