#!/bin/bash

export HOMEBREW_GITHUB_API_TOKEN="$(lpass show --password ApiKeys/HomebrewToken)"

brew cask install caffeine
brew cask install dropbox
brew cask install flux
brew cask install google-chrome
brew cask install hammerspoon
mkdir -p "$HOME/.hammerspoon"
ln -sf "$DOTFILES/hammerspoon/init.lua" "$HOME/.hammerspoon/init.lua"
brew cask install iterm2
brew cask install itsycal
brew cask install screenhero
brew cask install selfcontrol
brew cask install sonos
brew cask install tidal
brew cask install ynab
