---
- name: Installing tools
  condstall:
    package: "{{ item.pkg }}"
    binary: "{{ item.exe | default('') }}"
    installer: "{{ item.with }}"
    state: present
  with_items:
    - pkg: fd-find
      exe: fd
      with: rust
    - pkg: exa
      with: rust
    - pkg: ripgrep
      exe: rg
      with: rust
    - pkg: git-delta
      exe: delta
      with: rust
    - pkg: bat
      with: rust
    - pkg: precious
      with: rust
    - pkg: github.com/junegunn/fzf@latest
      exe: fzf
      with: go
    - pkg: github.com/itchyny/gojq/cmd/gojq@latest
      exe: gojq
      with: go
