---
- name: Installing default tools
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - man
    state: latest
  when: ansible_distribution == "Debian"
# TODO: Fix on homebrew

- name: Installing conda tools
  ansible.builtin.shell:
    cmd: |
      condstall --with conda --global --yes -- {{ item.pkg }}
    creates: "{{ lookup('env', 'CONDA_SYSTEM') }}/installers-conda/bin/{{ item.exe }}"
  with_items:
    - pkg: "fd-find"
      exe: "fd"

- name: Updating conda tools
  ansible.builtin.command:
    cmd: "conda update --name installers-conda --all --yes"
  changed_when: true

- name: Installing/updating cargo tools
  ansible.builtin.shell:
    cmd: |
      condstall --with rust --global --yes -- {{ item.pkg }} --locked
    creates: "{{ lookup('env', 'CARGO_HOME') }}/bin/{{ item.exe }}"
  with_items:
    - pkg: "exa --no-default-features"
      exe: "exa"
    - pkg: "bat"
      exe: "bat"
    - pkg: "ripgrep"
      exe: "rg"
    - pkg: "git-delta"
      exe: "delta"
    - pkg: "mdcat"
      exe: "mdcat"
   #- pkg: "fd-find"
   #  exe: "fd"
  changed_when: true

- name: Installing/updating go tools
  ansible.builtin.shell:
    cmd: |
      condstall --with go --global --yes -- github.com/{{ item.pkg }}
    creates: "{{ lookup('env', 'GOPATH') }}/bin/{{ item.exe }}"
  with_items:
    - pkg: "junegunn/fzf@latest"
      exe: "fzf"
    - pkg: "itchyny/gojq@latest"
      exe: "gojq"
  changed_when: true
