---
- name: Installing conda tools
  ansible.builtin.shell:
    cmd: |
      condstall --with conda --global --yes -- {{ item.pkg }}
    creates: "{{ lookup('env', 'CONDA_SYSTEM') }}/installers-conda/bin/{{ item.exe }}"
  with_items:
    - pkg: "fd-find"
      exe: "fd"
      distro: "Debian"
  when: item.distro == "" || ansible_distribution == item.distro

- name: Updating conda tools
  ansible.builtin.command:
    cmd: "conda update --name installers-conda --all --yes"
  changed_when: true

- name: Installing/updating cargo tools
  ansible.builtin.shell:
    cmd: |
      condstall --with rust --global --yes -- {{ item.pkg }} --locked
    creates: "{{ lookup('env', 'CARGO_HOME') }}/bin/{{ item.exe }}"
  with_items:
    - pkg: "exa --no-default-features"
      exe: "exa"
      distro: ""
    - pkg: "bat"
      exe: "bat"
      distro: ""
    - pkg: "ripgrep"
      exe: "rg"
      distro: ""
    - pkg: "git-delta"
      exe: "delta"
      distro: ""
    - pkg: "mdcat"
      exe: "mdcat"
      distro: ""
    - pkg: "fd-find"
      exe: "fd"
      distro: "MacOSX"
  changed_when: true
  when: item.distro == "" || ansible_distribution == item.distro

- name: Installing/updating go tools
  ansible.builtin.shell:
    cmd: |
      condstall --with go --global --yes -- github.com/{{ item.pkg }}
    creates: "{{ lookup('env', 'GOPATH') }}/bin/{{ item.exe }}"
  with_items:
    - pkg: "junegunn/fzf@latest"
      exe: "fzf"
    - pkg: "itchyny/gojq/cmd/gojq@latest"
      exe: "gojq"
  changed_when: true
