---
- name: Installing default progs
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - less
      - man
      - jq
      - fd-find
    state: latest
  when: ansible_distribution == "Debian"
# TODO: Fix on homebrew

- name: Installing cargo progs
  ansible.builtin.shell:
    cmd: |
      condstall --with rust --global --yes -- {{ item.pkg }} --locked
    creates: "{{ lookup('env', 'CARGO_HOME') }}/bin/{{ item.exe }}"
  with_items:
    - pkg: "exa --no-default-features"
      exe: "exa"
    - pkg: "bat"
      exe: "bat"
    - pkg: "ripgrep"
      exe: "rg"
    - pkg: "git-delta"
      exe: "delta"
   #- pkg: "fd-find"
   #  exe: "fd"

- name: Installing go progs
  ansible.builtin.shell:
    cmd: |
      condstall --with go --global --yes -- github.com/{{ item.pkg }}
    creates: "{{ lookup('env', 'GOPATH') }}/bin/{{ item.exe }}"
  with_items:
    - pkg: "junegunn/fzf@latest"
      exe: "fzf"
