#!/usr/bin/env bash

repo=$(git rev-parse --show-toplevel)

if [ ! -f "$repo/.pre-commit-config.yaml" ] && [ ! -f "$repo/lefthook.yml" ]; then
	echo -e >&2 "\033[103m\033[1;30m*** No pre-commit hooks for this repository! ***\033[0m"
	exit 0
fi

exit 0
