---
services:
  labs:
    build: .
    ports:
      - "8888:8888"
    user: root
    volumes:
      - code:/home/jovyan/work
    environment:
      - NB_UID=1111
      - NB_GID=1111
      - CHOWN_HOME=yes
volumes:
  code:
    external: true
    name: code
