---
- name: Make ports available
  ansible.builtin.file:
    src: /opt/local/bin
    dest: "{{ lookup('env', 'XDG_PKG_HOME') }}/ports"
    state: link

- name: Sync and update ports
  become: true
  community.general.macports:
    selfupdate: true
    upgrade: true

- name: Install/replace macos tools
  become: true
  community.general.macports:
    name:
      - bash
      - less
      - unzip
      - vim
      - zsh
    state: installed

- name: Install gnu tools
  become: true
  community.general.macports:
    name:
      - coreutils
      - diffutils
      - findutils
      - gawk
      - grep
      - gsed
      - gtime
    state: installed

- name: Link gnu bin dir
  ansible.builtin.file:
    src: /opt/local/libexec/gnubin
    dest: "{{ lookup('env', 'XDG_PKG_HOME') }}/gports"
    state: link
