---
- name: Install macos tools
  ansible.builtin.command:
    cmd: "port install -t -v {{ item.name }} {{ item.variants }}"
  with_items:
    - name: zsh
      variants: ""
    - name: less
      variants: ""
    - name: git
      variants: ""
  changed_when: true
