---
- name: Sync and update ports
  community.general.macports:
    selfupdate: yes
    upgrade: yes

- name: Install macos tools
  community.general.macports:
    name: "{{ ports }}"
    vars:
      ports:
        - zsh
        - git
        - gnutar
        - coreutils
    state: installed
