---
- name: Sync and update ports
  become: true
  community.general.macports:
    selfupdate: true
    upgrade: true

- name: Install/replace macos tools
  become: true
  community.general.macports:
    name:
      - bash
      - git
      - gnutar
      - gutils-suite
      - less
      - unzip
      - vim
      - zsh
    state: installed
