---
- name: Update conf to binary only
  become: true
  ansible.builtin.lineinfile:
    path: "/opt/local/etc/macports/macports.conf"
    regexp: "^#buildfromsource.*$"
    line: "buildfromsource never"

- name: Update conf application dir
  become: true
  ansible.builtin.lineinfile:
    path: "/opt/local/etc/macports/macports.conf"
    regexp: "^#applications_dir.*$"
    line: "applications_dir {{ lookup('env', 'XDG_PKG_HOME') }}/apps"

- name: Make port available
  ansible.builtin.file:
    src: "/opt/local/bin/port"
    dest: "{{ lookup('env', 'XDG_PKG_HOME') }}/ports/port"
    state: link
