---
- name: Latest macports
  ansible.builtin.git:
    repo: "https://github.com/macports/macports-base.git"
    version: "HEAD"
    force: true
    dest: "{{ lookup('env', 'XDG_DATA_HOME') }}/macports"
    single_branch: true
    depth: 1
  notify: "macports updated"

- name: Link macports bin dirs
  ansible.builtin.file:
    src: "{{ lookup('env', 'XDG_STATE_HOME') }}/{{ item.ports }}"
    dest: "{{ lookup('env', 'XDG_PKG_HOME') }}/{{ item.pkg }}"
    state: link
  with_items:
    - ports: "macports/bin"
      pkg: "ports"
    - ports: "macports/libexec/gnubin"
      pkg: "gports"
