#!/bin/bash
#
# Ensures that Dropbox is installed on this system
#
# Dependencies
source package-installer
source ensure-lastpass-cli

if package_installed dropbox-uploader; then
    echo 'Latest dropbox-uploader version installed'
else
    
	# Do a manual install
	git clone https://github.com/andreafabrizi/Dropbox-Uploader/
 	sudo mv Dropbox-Uploader/dropbox_uploader.sh /usr/bin/
 	pushd /usr/bin/
 	chmod +x dropbox_uploader.sh
 	popd

 	rm -fdr Dropbox-Uploader
fi

alias dbox='/usr/bin/dropbox_uploader.sh'

# We are setting these config values from lastpass so it "just works"
if [ ! -e ~/~/.dropbox_uploader ]; then
	echo '' > ~/.dropbox_uploader
	echo "APPKEY=$(lpass show --sync=now DropboxAuth/AppKey)" > ~/.dropbox_uploader
	echo "APPSECRET=$(lpass show --sync=now DropboxAuth/AppSecret)" >> ~/.dropbox_uploader
	echo "ACCESS_LEVEL=dropbox" >> ~/.dropbox_uploader
	echo "OAUTH_ACCESS_TOKEN=$(lpass show --sync=now DropboxAuth/OAuthToken)" >> ~/.dropbox_uploader
	echo "OAUTH_ACCESS_TOKEN_SECRET=$(lpass show --sync=now DropboxAuth/OAuthSecret)" >> ~/.dropbox_uploader
fi