#!/bin/bash
#
# Ensures that Lastpass is installed on this system
#
# Dependencies
source package-installer

if package_installed lastpass-cli; then
    echo 'Latest lastpass-cli version installed'

    if lpass login $LASTPASS_USERNAME; then
        lpass sync
        return 0
    fi
fi

echo 'Something went wrong and you might not have lastpass-cli :('
exit 1
