#!/bin/bash
#
# Ensures that the distros package manager is installed
# Ensures that additional package manager components are installed
# Ensures that the PACKAGE_MANAGER environment variable is set
#

if [ -z "$PACKAGE_MANAGER" ]; then
    echo 'No $PACKAGE_MANAGER found'

    if [ -e "$(which pacman)" ]; then
        echo "We're on Arch!"
        export PACKAGE_MANAGER=pacman
    elif [ -e "$(which brew)" ] || [[ "$OSTYPE" == "darwin"* ]]; then
        echo "We're on Mac!"
        export PACKAGE_MANAGER=homebrew
    fi

else
    echo "$PACKAGE_MANAGER found"
fi
