#!/bin/bash
# Exports package_installed
#
# Dependencies
source ensure-package-manager

# Installs the requested packege if available
# Arguments
#   $1 package-name 
#   $2 additional-package-source TODO: figure out how to handle additional package sources
# Returns
#   0 Package is definitely installed
#   1 Package is probably not installed
package_installed () {

    if [ ! "$1" ]; then
        echo "You must provide a package name"
    	return 1
    fi
    
    
    case "$(get_package_manager)" in
        "pacman")
    		pacman -Syu
    		packer -Syu
            if [ $(pacman -Ss $1 | grep '/$1 ') ]; then
            	echo "Installing $1 from pacman"
            	pacman -S $1
            	return 0
            fi
            if [ $(packer -Ss $1 | grep '/$1 ') ]; then
            	echo "Installing $1 from packer"
            	packer -S $1
            	return 0
            fi 
        ;;
        "homebrew")
    		brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
    		if [ $(brew search $1 | grep $1) ]; then
    			
    			if [ $(brew list | grep $1) ]; then
    				echo "Upgrading $1 from homebrew"
            		brew upgrade $1
            	else
            		echo "Installing $1 from homebrew"
            		brew install $1	
    			fi
            	
            	return 0
            fi
            if [ $(brew cask search $1 | grep $1) ]; then
            	
            	if [ $(brew cask list | grep $1) ]; then
    				echo "Upgrading $1 from homebrew cask"
            		brew cask install --force $1
            	else
            		echo "Installing $1 from homebrew cask"
            		brew cask install $1	
    			fi
            	
            	return 0
            fi 
        ;;
        *)
    		echo 'We dont know what $PACKAGE_MANAGER you are using!'
            return 1
        ;;
    esac
    
    
        echo "We couldn't find $1 using $PACKAGE_MANAGER!"
        return 1
}