#!/bin/bash
#
# Sets things up for the installation script
#

requires () {
  source $@
}
export -f requires

for thisPath in \
  "$(pwd)/src/dotfiles" \
  "$(pwd)/src/applications" \
  "$(pwd)/src/utilities" \
  "$(pwd)/src/ssh-keys" \
  "$(pwd)/src/package-management" \
  "$(pwd)/dotfiles/git" \
  "$(pwd)/dotfiles/zshrc"; do
  
  case ":$PATH:" in
    *":$thisPath:"*) :;; # already there
    *) PATH="$PATH:$thisPath";;
  esac
done

export DOTFILES_DIR="$(pwd)/dotfiles"