#!/bin/bash
log_step 'Ensuring latest bitwarden is installed and configured'

bw_url='https://vault.bitwarden.com/download/?app=cli&platform=linux'

log_trace 'Getting latest bw file name'
bw_linux_version=$(wget --server-response -q -O - "$bw_url" 2>&1 | 
    grep "Content-Disposition:" | tail -1 | 
    awk -F"filename=" '{print $2}')

mkdir -p "$HOME/downloads"
if [ ! -f "$HOME/downloads/$bw_linux_version" ]; then
    log_trace 'Downloading latest bw executable'
    wget --content-disposition "$bw_url" -P "$HOME/downloads"

    log_trace 'Extracting executable to /usr/local/bin'
    unzip -o -p "$HOME/downloads/$bw_linux_version" bw > "$HOME/downloads/bw"
    # for some reason unzip can't write directly to usr/local/bin : /
    sudo cp "$HOME/downloads/bw" /usr/local/bin/bw
    sudo chmod +x /usr/local/bin/bw
fi

bw login brycekbargar@gmail.com

log_message 'Latest bitwarden is installed and configured'
