#!/bin/bash
log_step 'Ensuring docker is installed and configured'

log_trace 'Getting gpg key'
wget -qO - https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

log_trace 'Installing docker'
sudo apt update
sudo apt --yes install docker-ce docker-ce-cli containerd.io

log_trace 'Creating fstab file (wsl2 will do this eventually)'
sudo touch /etc/fstab

log_trace 'Use legacy iptablles (debian will catch up eventually)'
sudo update-alternatives --config iptables

log_trace 'Making me a docker user'
sudo usermod -aG docker $USER

log_message 'Docker installed and configured'
