#!/bin/bash
log_step 'Ensuring vim is installed and minimally configure'

log_trace 'Installing vim'
sudo apt --yes install vim-gtk

log_trace 'Loading vim-sensible plugin'
mkdir -p "$HOME/.vim/pack/tpope/start"
pushd "$HOME/.vim/pack/tpope/start"
  if [ ! -d "sensible" ]; then
    git clone https://tpope.io/vim/sensible.git
  fi
  pushd sensible
    git fetch --prune
    git reset --hard origin/master
  popd
popd

log_message 'Vim is installed and minimally configured'
