#!/bin/bash
log_step 'Ensuring go is installed with tools'

log_trace 'Installing go'
sudo apt --yes install -t unstable golang

log_trace 'Installing go tools'
go get -u github.com/tj/go-search
go get -u github.com/mfridman/tparse

log_message 'Go is installed with tools'
