#!/bin/bash

MYEMAIL="brycekbargar@gmail.com"
# The following only need to be overriden if they aren't the same as above
# LASTPASS_USERNAME=
# GIT_NAME=
# GIT_EMAIL=

export LASTPASS_USERNAME=${LASTPASS_USERNAME:-"$MYEMAIL"}
export GIT_NAME=${GIT_NAME:-$(whoami)}
export GIT_EMAIL=${GIT_EMAIL:-"$MYEMAIL"}
