#!/bin/bash
log_step 'Ensuring git is configured'

log_trace 'Symlinking  my gitconfig'
sudo ln -sf "$DOTFILES/git/.gitconfig" "$HOME/.gitconfig"

log_trace 'Setting up author/committer globals'
grep "GIT_AUTHOR_NAME" "$HOME/.zshrcfiles/local.zsh" &> /dev/null || \
echo "export GIT_AUTHOR_NAME=bryce" >>  "$HOME/.zshrcfiles/local.zsh"
grep "GIT_AUTHOR_EMAIL" "$HOME/.zshrcfiles/local.zsh" &> /dev/null || \
echo "export GIT_AUTHOR_EMAIL=brycekbargar@gmail.com" >>  "$HOME/.zshrcfiles/local.zsh"
grep "GIT_COMMITTER_NAME" "$HOME/.zshrcfiles/local.zsh" &> /dev/null || \
echo "export GIT_COMMITTER_NAME=bryce" >>  "$HOME/.zshrcfiles/local.zsh"
grep "GIT_COMMITTER_EMAIL" "$HOME/.zshrcfiles/local.zsh" &> /dev/null || \
echo "export GIT_COMMITTER_EMAIL=brycekbargar@gmail.com" >>  "$HOME/.zshrcfiles/local.zsh"

for thisFileName in "$DOTFILES/git/bin/"*; do
    thisFile=$(basename "$thisFileName")
    log_trace "Symlinking $thisFile"

    sudo ln -sf "$DOTFILES/git/bin/$thisFile" "/usr/local/bin/$thisFile"

    log_message "$thisFile symlinked"
done

log_message 'Git is configured'
