#!/bin/bash
log_step 'Ensuring ssh is enabled and ssh-keys are downloaded from bitwarden'

log_trace 'Installing openssh-client'
sudo apt --yes install openssh-client
mkdir -p $HOME/.ssh

log_trace 'Downloading keys from bitwarden'
session="$(bw unlock --raw)"
keys="$(bw list items --folderid 5f327073-d3b6-4940-9783-a9db0022589e --session "$session" |
    jq -r --arg SESSION "$session" --arg HOME "$HOME" '
        map({ "itemid":.id, "attachment": .attachments[] })
        | map("bw get attachment \(.attachment.id) --itemid \(.itemid) --output \($HOME)/.ssh/\(.attachment.fileName) --session \($SESSION);")
        | .[] ')"
eval $keys
bw lock

log_trace 'Updating ssh file permissions'
chmod 600 "$HOME"/.ssh/*

log_trace 'Updating git remote to ssh'
git remote set-url origin git@github.com:brycekbargar/debian-dotfiles.git

log_message 'Ssh is enabled and ssh-keys are downloaded from bitwarden'
