export \
    INPUTRC="$XDG_CONFIG_HOME/.inputrc"
export \
    NPM_CONFIG_CACHE="$XDG_CACHE_HOME/npm" \
    NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/.npmrc" \
    NPM_CONFIG_INIT_MODULES="$XDG_CONFIG_HOME/npm/.npm.init.js" \
export \
    PIPX_HOME="$XDG_STATE_HOME/pipx"
export \
    BITWARDENCLI_APPDATA_DIR="$XDG_STATE_HOME/bw"
export \
    RIPGREP_CONFIG_PATH="$XDG_CONFIG_HOME/ripgrep"
export \
    KITTY_CONFIG_DIRECTORY="$XDG_CONFIG_HOME" \
    KITTY_CACHE_DIRECTORY="$XDG_CACHE_HOME/kitty"

