---
- name: Run with home configuration
  hosts: localhost
  vars:
    dotfiles: "{{ playbook_dir }}/.."
    zsh: /usr/bin/zsh
  roles:
    - prepare
    - debian
    - conda
    - zsh
    - vim
    - tools
    - neovim
