---
- hosts: localhost
  vars:
    dotfiles: "{{ playbook_dir }}/.."
  roles:
    - prepare
    - debian
    - conda
    - role: zsh
      vars:
        zsh: "/usr/bin/zsh"
    - vim
    - neovim
    - tools
