---
- hosts: localhost
  vars:
    dotfiles: "{{ playbook_dir }}/../"
  tasks:
    - name: Install python3-apt
      become: true
      ansible.builtin.command:
        cmd: "apt install python3-apt --yes"
      changed_when: true
    - name: Run roles
      block:
        - ansible.builtin.import_role:
            name: debian
        - ansible.builtin.import_role:
            name: conda
        - ansible.builtin.import_role:
            name: neovim
      always:
        - name: Remove python3-apt
          become: true
          ansible.builtin.command:
            cmd: "apt --purge autoremove python3-apt python3 --yes"
          changed_when: true
