---
- hosts: localhost
  vars:
    dotfiles: "{{ playbook_dir }}/.."
  pre_tasks: 
    - name: Install python3-apt
      become: true
      ansible.builtin.command:
        cmd: "apt install python3-apt --yes"
      changed_when: true
    - name: Run Debian Setup
      block:
        - ansible.builtin.import_role:
            name: debian
          vars:
            debian: "{{ playbook_dir }}/../debian"
      always:
        - name: Remove python3-apt
          become: true
          ansible.builtin.command:
            cmd: "apt --purge autoremove python3-apt python3 --yes"
          changed_when: true
  roles:
    - prepare
    - conda
    - zsh
    - vim
    - neovim
    - tools
