#!/usr/bin/env bash

while [[ "$#" -gt 0 ]]; do
    case "$1" in
    -u | --using)
        RUNTIME="$2"
        shift 2
        ;;
    -p | --package)
        PACKAGE="$2"
        shift 2
        ;;

    --)
        shift 1
        break
        ;;

    *)
        echo >&2 "Unknown option: $1"
        exit 1
        ;;

    esac
done

# TODO: Error handing and param validation

case $RUNTIME in
nodejs)
    CMD="conda run --name runtimes-nodejs --no-capture-output npm exec --yes"
    if [[ -n "$PACKAGE" ]]; then
        CMD="$CMD --package='$PACKAGE'"
    fi
    CMD="$CMD -- $@"
    ;;

python)
    CMD="conda run --name runtimes-python --no-capture-output pipx run"
    if [[ -n "$PACKAGE" ]]; then
        CMD="$CMD --spec '$PACKAGE'"
    fi
    CMD="$CMD $@"
    ;;

*)
    echo >&2 "Unknown runtime: $RUNTIME"
    exit 1
    ;;

esac

eval "$CMD"
